// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAql0N552l-u2NhnlhbCQM8Z_FbcbFeNkc',
    appId: '1:777971424119:web:813fc1b578b6bb02401f72',
    messagingSenderId: '777971424119',
    projectId: 'pt-auth-f47aa',
    authDomain: 'pt-auth-f47aa.firebaseapp.com',
    storageBucket: 'pt-auth-f47aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg8LmGh_z6HCknykU3PGWv1-ywBHJup18',
    appId: '1:777971424119:android:4863b1a1e10e6490401f72',
    messagingSenderId: '777971424119',
    projectId: 'pt-auth-f47aa',
    storageBucket: 'pt-auth-f47aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA2BCiW82gctEoIlMIKqjF5h-kOyHErv4',
    appId: '1:777971424119:ios:980e7ba9948a0ffa401f72',
    messagingSenderId: '777971424119',
    projectId: 'pt-auth-f47aa',
    storageBucket: 'pt-auth-f47aa.appspot.com',
    iosBundleId: 'com.example.vaultcash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA2BCiW82gctEoIlMIKqjF5h-kOyHErv4',
    appId: '1:777971424119:ios:980e7ba9948a0ffa401f72',
    messagingSenderId: '777971424119',
    projectId: 'pt-auth-f47aa',
    storageBucket: 'pt-auth-f47aa.appspot.com',
    iosBundleId: 'com.example.vaultcash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAql0N552l-u2NhnlhbCQM8Z_FbcbFeNkc',
    appId: '1:777971424119:web:4b654b0d0b215298401f72',
    messagingSenderId: '777971424119',
    projectId: 'pt-auth-f47aa',
    authDomain: 'pt-auth-f47aa.firebaseapp.com',
    storageBucket: 'pt-auth-f47aa.appspot.com',
  );
}
